function [pd,M]=normalize_points(p)
%except the points as (x:y:1) as the output generated by the RANSAC in prev step. 
c = mean(p(:,1:2)); 
   
a= eye(3);
a(1,3) = -c(1); 
a(2,3) = -c(2); 

sX= max(abs(p(:,1)));
sY= max(abs(p(:,2)));

scale = eye(3);
scale(1,1)=1/sX;
scale(2,2)=1/sY; 
                
M = scale * a;
pd=(M*p')';
    
end
